num1=int(input("Enter first number: "))
num2=int(input("Enter second number: "))
print("Bitwise AND:", num1 & num2)
print("Bitwise OR:", num1 | num2)
print("Bitwise XOR:", num1 ^ num2)
print("Bitwise NOT (num1):", ~num1)
print("Bitwise NOT (num2):", ~num2)
print("Left Shift (num1 << 2):", num1 << 2)
print("Right Shift (num1 >> 2):", num1 >> 2)
print("Left Shift (num2 << 2):", num2 << 2)
print("Right Shift (num2 >> 2):", num2 >> 2)
print("Bitwise AND with NOT num1:", num1 & ~num2)
print("Bitwise AND with NOT num2:", num2 & ~num1)